### ISSUE TITLE
Error when unmarshaling types.Date query param

### ISSUE THREAD

**Issue by 0gener** [oapi-codegen/runtime#21]
I am using `oapi-codegen` to generate the models for a date query param:
```yaml
- name: date_from
   in: query
   schema:
   type: string
   format: date
```

This generates something like this:
```go
type Params struct {
	DateFrom   *openapi_types.Date `form:"date_from,omitempty" json:"date_from,omitempty"`
}
```

And then when binding the query params I get an error:
```go
var queryParams models.Params
if err := c.BindQuery(&queryParams); err != nil {
    c.AbortWithStatusJSON(http.StatusBadRequest, api.NewError(err.Error()))
    return
}
```

Request URL: /endpoint?date_from=2023-01-01
Error: `invalid character '-' after top-level value`
