### ISSUE TITLE
Large integers inside style=deepObject struct mashaled as floats

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [oapi-codegen/runtime#28]
Given a parameter like this:
```yaml
        - name: foo
          in: query
          style: deepObject
          schema:
            type: object
            properties:
              min:
                type: integer
                format: int64
              max:
                type: integer
                format: int64
```
The generated client code:
1. Marshals the struct to JSON
2. Parses the JSON back as a `map[string]any`, resulting in the numbers being converted to `float64` -- already not great her I think
3. Constructs the query parameter values using `fmt.Sprintf("=%v, ...)` resulting in the _integer_ parameter using floating point "e" notation if it's greater than ~ 100000
4. The generated server then refuses to parse values like `1.23454678e9` as not valid string representations of integers

Item 2 happens in `MarshalDeepObject`: https://github.com/oapi-codegen/runtime/blob/35e80354e30b38a82a5b1b681f48e560c0194cb5/deepobject.go#L75

Item 3 happens just above in `marshalDeepObject`: https://github.com/oapi-codegen/runtime/blob/35e80354e30b38a82a5b1b681f48e560c0194cb5/deepobject.go#L58

I think that, if it has to go through the unfortunate JSON loop, it should use a `json.Decoder` with [`UseNumber()`](https://pkg.go.dev/encoding/json#Decoder.UseNumber) applied so that numbers are retained at full fidelity.
