### ISSUE TITLE
Support for deepObject nested object and array of primitives query parameters

### ISSUE THREAD

**Issue by danicc097** [oapi-codegen/runtime#36]
Due to the recent changes of https://github.com/getkin/kin-openapi/pull/911, I was wondering if you'd be willing to support the same functionality, i.e. nested objects with arrays of primitives (for `deepObject` `explode: true` params). Arrays of objects are purposedly not supported

`runtime` currently parses nested objects with a primitive properly, e.g. `?nested[obj][nestedObj]=string`
```yaml
        - in: query
          name: nested
          style: deepObject
          explode: true
          allowReserved: true
          schema:
            type: object
            properties:
              obj:
                type: object
                properties:
                  nestedObj:
                    type: string 
```

but it fails on a nested array (either ignoring an element when given one, or erroring out: https://github.com/oapi-codegen/runtime/blob/main/deepobject.go#L137).
It also errors out when the nested array field has a sibling field:
`Invalid format for parameter nested: error assigning value to destination: error assigning field [obj]: field [authors] is not present in destination object`
```jsonc
// - in: query
//   name: nested
//   style: deepObject
//   explode: true
//   allowReserved: true
//   schema:
//     type: object
//     properties:
//       obj:
//         type: object
//         properties:
//           nestedObj:
//             type: string
//           authors:
//             type: array
//             items:
//               type: string
{
  "obj": {
    "nestedObj": "string",
    "authors": [
      "string"
    ]
  }
}
```

As far as I've seen, it would also need changes to `marshalDeepObject`, since it adds array subscripts that would interfere with nested object keys, e.g. it marshals `p[onas][Names][0]=Bill&p[onas][Names][1]=Frank` instead of just `p[onas][Names]=Bill&p[onas][Names]=Frank`. 

Probably missing other stuff. Please let me know if you have some thoughts on this. Some examples:
-  https://github.com/getkin/kin-openapi/blob/05ccac23d287d8b25daf7a897e8868291ec53e81/openapi3filter/req_resp_decoder_test.go#L782
- https://github.com/getkin/kin-openapi/blob/05ccac23d287d8b25daf7a897e8868291ec53e81/openapi3filter/req_resp_decoder_test.go#L812
