### ISSUE TITLE
runtime.StyleParamWithLocation for map[string]int fails with "map not of type map[string]interface{}"

### ISSUE THREAD

**Issue by andnow873** [oapi-codegen/runtime#37]
```
# spec
    PriorityFilter:
      name: priority
      in: query
      schema:
        type: object
        additionalProperties:
          type: integer
```

```
// models 

// PriorityFilter defines model for PriorityFilter.
type PriorityFilter map[string]int

// GetMessagesParams defines parameters for GetMessages.
type GetMessagesParams struct {
	Priority *PriorityFilter `form:"priority,omitempty" json:"priority,omitempty"`
}
```

```
// using client

pf := PriorityFilter(map[string]int{"gt": 100})
_, err := client.GetMessages(ctx, &GetMessagesParams{
	Priority: &pf,
})
if err != nil {
	t.Fatalf("get messages: %s", err)
}

// fails with error: get messages: map not of type map[string]interface{}
```
It fails on call `if queryFrag, err := runtime.StyleParamWithLocation("form", true, "priority", runtime.ParamLocationQuery, *params.Priority); err != nil {
				return nil, err
			}`
