### ISSUE TITLE
Field type=string, format=email validation fails

### ISSUE THREAD

**Issue by vojtechmares** [oapi-codegen/runtime#43]
Hello,

I am having an issue with validating the email format of string. I am trying to pass regular email like `john.doe@example.com` or my email, but no matter what, I am getting a validation error:

```
json: error calling MarshalJSON for type types.Email: email: failed to pass regex validation
```

My schema

```yaml
# ...
        email:
          type: string
          format: email
# ...
```

I am using Fiber as my HTTP server. Golang 1.22.3 on macOS (`darwin/arm64`).
